blog:
  status:
    draft: 0
    published: 1
  suggest:
    unavailable: 0
    available: 1

reaction:
  rate:
    like: 0
    gratitude: 1
    bored: 2
    disappointed: 3

default_upload_icon: default.png